spring:
  profiles:
    active:
    - redis

---
spring:
  profiles: redis
  application:
    name: configservice-rides
    
---
spring:
  profiles: mybatis
  application:
    name: configservice-mybatis