spring:
  profiles:
    active:
    - redis

---
spring:
  profiles: redis
  application:
    name: configservice-rides
    
---
spring:
  profiles: mybatis
  application:
    name: configservice-mybatis
    #数据库连接信息
  datasource:
    url: jadc:mysql://127.0.0.1:3306/newer?userSSL=false
    username: root
    password: root
